require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuditsController do

  # This should return the minimal set of attributes required to create a valid
  # Audit. As you add validations to Audit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all audits as @audits" do
      audit = Audit.create! valid_attributes
      get :index
      assigns(:audits).should eq([audit])
    end
  end

  describe "GET show" do
    it "assigns the requested audit as @audit" do
      audit = Audit.create! valid_attributes
      get :show, :id => audit.id.to_s
      assigns(:audit).should eq(audit)
    end
  end

  describe "GET new" do
    it "assigns a new audit as @audit" do
      get :new
      assigns(:audit).should be_a_new(Audit)
    end
  end

  describe "GET edit" do
    it "assigns the requested audit as @audit" do
      audit = Audit.create! valid_attributes
      get :edit, :id => audit.id.to_s
      assigns(:audit).should eq(audit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Audit" do
        expect {
          post :create, :audit => valid_attributes
        }.to change(Audit, :count).by(1)
      end

      it "assigns a newly created audit as @audit" do
        post :create, :audit => valid_attributes
        assigns(:audit).should be_a(Audit)
        assigns(:audit).should be_persisted
      end

      it "redirects to the created audit" do
        post :create, :audit => valid_attributes
        response.should redirect_to(Audit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved audit as @audit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Audit.any_instance.stub(:save).and_return(false)
        post :create, :audit => {}
        assigns(:audit).should be_a_new(Audit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Audit.any_instance.stub(:save).and_return(false)
        post :create, :audit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested audit" do
        audit = Audit.create! valid_attributes
        # Assuming there are no other audits in the database, this
        # specifies that the Audit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Audit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => audit.id, :audit => {'these' => 'params'}
      end

      it "assigns the requested audit as @audit" do
        audit = Audit.create! valid_attributes
        put :update, :id => audit.id, :audit => valid_attributes
        assigns(:audit).should eq(audit)
      end

      it "redirects to the audit" do
        audit = Audit.create! valid_attributes
        put :update, :id => audit.id, :audit => valid_attributes
        response.should redirect_to(audit)
      end
    end

    describe "with invalid params" do
      it "assigns the audit as @audit" do
        audit = Audit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Audit.any_instance.stub(:save).and_return(false)
        put :update, :id => audit.id.to_s, :audit => {}
        assigns(:audit).should eq(audit)
      end

      it "re-renders the 'edit' template" do
        audit = Audit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Audit.any_instance.stub(:save).and_return(false)
        put :update, :id => audit.id.to_s, :audit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested audit" do
      audit = Audit.create! valid_attributes
      expect {
        delete :destroy, :id => audit.id.to_s
      }.to change(Audit, :count).by(-1)
    end

    it "redirects to the audits list" do
      audit = Audit.create! valid_attributes
      delete :destroy, :id => audit.id.to_s
      response.should redirect_to(audits_url)
    end
  end

end
