require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntitySchemasController do

  # This should return the minimal set of attributes required to create a valid
  # EntitySchema. As you add validations to EntitySchema, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # describe "GET index" do
  #   it "assigns all entity_schemas as @entity_schemas" do
  #     entity_schema = EntitySchema.create! valid_attributes
  #     get :index
  #     assigns(:entity_schemas).should eq([entity_schema])
  #   end
  # end

  describe "GET show" do
    it "assigns the requested entity_schema as @entity_schema" do
      entity_schema = EntitySchema.create! valid_attributes
      get :show, :id => entity_schema.id.to_s
      assigns(:entity_schema).should eq(entity_schema)
    end
  end

  describe "GET new" do
    it "assigns a new entity_schema as @entity_schema" do
      get :new
      assigns(:entity_schema).should be_a_new(EntitySchema)
    end
  end

  describe "GET edit" do
    it "assigns the requested entity_schema as @entity_schema" do
      entity_schema = EntitySchema.create! valid_attributes
      get :edit, :id => entity_schema.id.to_s
      assigns(:entity_schema).should eq(entity_schema)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntitySchema" do
        expect {
          post :create, :entity_schema => valid_attributes
        }.to change(EntitySchema, :count).by(1)
      end

      it "assigns a newly created entity_schema as @entity_schema" do
        post :create, :entity_schema => valid_attributes
        assigns(:entity_schema).should be_a(EntitySchema)
        assigns(:entity_schema).should be_persisted
      end

      it "redirects to the created entity_schema" do
        post :create, :entity_schema => valid_attributes
        response.should redirect_to(EntitySchema.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entity_schema as @entity_schema" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntitySchema.any_instance.stub(:save).and_return(false)
        post :create, :entity_schema => {}
        assigns(:entity_schema).should be_a_new(EntitySchema)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntitySchema.any_instance.stub(:save).and_return(false)
        post :create, :entity_schema => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entity_schema" do
        entity_schema = EntitySchema.create! valid_attributes
        # Assuming there are no other entity_schemas in the database, this
        # specifies that the EntitySchema created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntitySchema.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => entity_schema.id, :entity_schema => {'these' => 'params'}
      end

      it "assigns the requested entity_schema as @entity_schema" do
        entity_schema = EntitySchema.create! valid_attributes
        put :update, :id => entity_schema.id, :entity_schema => valid_attributes
        assigns(:entity_schema).should eq(entity_schema)
      end

      it "redirects to the entity_schema" do
        entity_schema = EntitySchema.create! valid_attributes
        put :update, :id => entity_schema.id, :entity_schema => valid_attributes
        response.should redirect_to(entity_schema)
      end
    end

    describe "with invalid params" do
      it "assigns the entity_schema as @entity_schema" do
        entity_schema = EntitySchema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntitySchema.any_instance.stub(:save).and_return(false)
        put :update, :id => entity_schema.id.to_s, :entity_schema => {}
        assigns(:entity_schema).should eq(entity_schema)
      end

      it "re-renders the 'edit' template" do
        entity_schema = EntitySchema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntitySchema.any_instance.stub(:save).and_return(false)
        put :update, :id => entity_schema.id.to_s, :entity_schema => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entity_schema" do
      entity_schema = EntitySchema.create! valid_attributes
      expect {
        delete :destroy, :id => entity_schema.id.to_s
      }.to change(EntitySchema, :count).by(-1)
    end

    it "redirects to the entity_schemas list" do
      entity_schema = EntitySchema.create! valid_attributes
      delete :destroy, :id => entity_schema.id.to_s
      response.should redirect_to(entity_schemas_url)
    end
  end

end
