require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhysicalRacksController do

  # This should return the minimal set of attributes required to create a valid
  # PhysicalRack. As you add validations to PhysicalRack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      index: 1,
      name: 'rackucious'
    }
  end

  describe "GET index" do
    it "assigns all physical_racks as @physical_racks" do
      physical_rack = PhysicalRack.create! valid_attributes
      get :index
      assigns(:physical_racks).should eq(PhysicalRack.all)
    end
  end

  describe "GET show" do
    it "assigns the requested physical_rack as @physical_rack" do
      physical_rack = PhysicalRack.create! valid_attributes
      get :show, :id => physical_rack.id.to_s
      assigns(:physical_rack).should eq(physical_rack)
    end
  end

  describe "GET new" do
    it "assigns a new physical_rack as @physical_rack" do
      get :new
      assigns(:physical_rack).should be_a_new(PhysicalRack)
    end
  end

  describe "GET edit" do
    it "assigns the requested physical_rack as @physical_rack" do
      physical_rack = PhysicalRack.create! valid_attributes
      get :edit, :id => physical_rack.id.to_s
      assigns(:physical_rack).should eq(physical_rack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PhysicalRack" do
        expect {
          post :create, :physical_rack => valid_attributes
        }.to change(PhysicalRack, :count).by(1)
      end

      it "assigns a newly created physical_rack as @physical_rack" do
        post :create, :physical_rack => valid_attributes
        assigns(:physical_rack).should be_a(PhysicalRack)
        assigns(:physical_rack).should be_persisted
      end

      it "redirects to the created physical_rack" do
        post :create, :physical_rack => valid_attributes
        response.should redirect_to(PhysicalRack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved physical_rack as @physical_rack" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhysicalRack.any_instance.stub(:save).and_return(false)
        post :create, :physical_rack => {}
        assigns(:physical_rack).should be_a_new(PhysicalRack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhysicalRack.any_instance.stub(:save).and_return(false)
        post :create, :physical_rack => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested physical_rack" do
        physical_rack = PhysicalRack.create! valid_attributes
        PhysicalRack.any_instance.should_receive(:attributes=).with({'these' => 'params'})
        PhysicalRack.any_instance.should_receive(:save)
        put :update, :id => physical_rack.id, :physical_rack => {'these' => 'params'}
      end

      it "assigns the requested physical_rack as @physical_rack" do
        physical_rack = PhysicalRack.create! valid_attributes
        put :update, :id => physical_rack.id, :physical_rack => valid_attributes
        assigns(:physical_rack).should eq(physical_rack)
      end

      it "redirects to the physical_rack" do
        physical_rack = PhysicalRack.create! valid_attributes
        put :update, :id => physical_rack.id, :physical_rack => valid_attributes
        response.should redirect_to(physical_rack)
      end
    end

    describe "with invalid params" do
      it "assigns the physical_rack as @physical_rack" do
        physical_rack = PhysicalRack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhysicalRack.any_instance.stub(:save).and_return(false)
        put :update, :id => physical_rack.id.to_s, :physical_rack => {}
        assigns(:physical_rack).should eq(physical_rack)
      end

      it "re-renders the 'edit' template" do
        physical_rack = PhysicalRack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhysicalRack.any_instance.stub(:save).and_return(false)
        put :update, :id => physical_rack.id.to_s, :physical_rack => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested physical_rack" do
      physical_rack = PhysicalRack.create! valid_attributes
      expect {
        delete :destroy, :id => physical_rack.id.to_s
      }.to change(PhysicalRack, :count).by(-1)
    end

    it "redirects to the physical_racks list" do
      physical_rack = PhysicalRack.create! valid_attributes
      delete :destroy, :id => physical_rack.id.to_s
      response.should redirect_to(physical_racks_url)
    end
  end

end
