require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsController do

  # This should return the minimal set of attributes required to create a valid
  # U. As you add validations to U, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all us as @us" do
      u = U.create! valid_attributes
      get :index
      assigns(:us).should eq([u])
    end
  end

  describe "GET show" do
    it "assigns the requested u as @u" do
      u = U.create! valid_attributes
      get :show, :id => u.id.to_s
      assigns(:u).should eq(u)
    end
  end

  describe "GET new" do
    it "assigns a new u as @u" do
      get :new
      assigns(:u).should be_a_new(U)
    end
  end

  describe "GET edit" do
    it "assigns the requested u as @u" do
      u = U.create! valid_attributes
      get :edit, :id => u.id.to_s
      assigns(:u).should eq(u)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new U" do
        expect {
          post :create, :u => valid_attributes
        }.to change(U, :count).by(1)
      end

      it "assigns a newly created u as @u" do
        post :create, :u => valid_attributes
        assigns(:u).should be_a(U)
        assigns(:u).should be_persisted
      end

      it "redirects to the created u" do
        post :create, :u => valid_attributes
        response.should redirect_to(U.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved u as @u" do
        # Trigger the behavior that occurs when invalid params are submitted
        U.any_instance.stub(:save).and_return(false)
        post :create, :u => {}
        assigns(:u).should be_a_new(U)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        U.any_instance.stub(:save).and_return(false)
        post :create, :u => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested u" do
        u = U.create! valid_attributes
        # Assuming there are no other us in the database, this
        # specifies that the U created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        U.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => u.id, :u => {'these' => 'params'}
      end

      it "assigns the requested u as @u" do
        u = U.create! valid_attributes
        put :update, :id => u.id, :u => valid_attributes
        assigns(:u).should eq(u)
      end

      it "redirects to the u" do
        u = U.create! valid_attributes
        put :update, :id => u.id, :u => valid_attributes
        response.should redirect_to(u)
      end
    end

    describe "with invalid params" do
      it "assigns the u as @u" do
        u = U.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        U.any_instance.stub(:save).and_return(false)
        put :update, :id => u.id.to_s, :u => {}
        assigns(:u).should eq(u)
      end

      it "re-renders the 'edit' template" do
        u = U.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        U.any_instance.stub(:save).and_return(false)
        put :update, :id => u.id.to_s, :u => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested u" do
      u = U.create! valid_attributes
      expect {
        delete :destroy, :id => u.id.to_s
      }.to change(U, :count).by(-1)
    end

    it "redirects to the us list" do
      u = U.create! valid_attributes
      delete :destroy, :id => u.id.to_s
      response.should redirect_to(us_url)
    end
  end

end
